# 
#  Configuration
#
#
air_spells:
- airblast
- airbomb
- suction
- tornade
- poussee
- airshield
- enhancedspeed
- airscooter
- breathofwind
air_spells_bq:
- air_airblast
- air_bomb
- air_suction
- air_tornado
- air_poussee
- air_shield
- air_enhancedspeed
- air_scooter
- air_breathofwind
earth_spells:
- tossi
- earthblock
- breche
- compression
- sandspout
- earthsmash
- earthquaki
- collapsi
- earthline
- durci
earth_spells_bq:
- earth_tossi
- earth_earthblock
- earth_breche
- earth_compression
- earth_sandspout
- earth_earthsmash
- earth_earthquaki
- earth_collapsi
- earth_earthline
- earth_durci
grades_bq:
- intendant_done
- grade_ecuyer
- grade_chevalier
- grade_champion
- grade_seigneur
- grade_banneret
- grade_baron
- grade_vicomte
- grade_comte
- grade_marquis
- grade_duc
- grade_prince
- grade_legende
grades_noms:
- Citoyen
- Écuyer
- Chevalier
- Champion
- Seigneur
- Banneret
- Baron
- Vicomte
- Comte
- Marquis
- Duc
- Prince
- Légende
metiers_bq:
- metier_poings
- metier_epees
- metier_haches
- metier_arc
- metier_alchimiste
- metier_acrobate
- metier_peche
- metier_apprivoiseur
- metier_herboriste
- metier_mineur
- metier_reparation
- metier_excavation
- metier_bucheron
metiers_noms:
- Pugiliste
- Épéiste
- Milicien
- Archer
- Alchimiste
- Acrobate
- Pêcheur
- Apprivoiseur
- Herboriste
- Mineur
- Réparateur
- Excavateur
- Bûcheron
metiers_competences:
- unarmed
- swords
- axes
- archery
- alchemy
- acrobatics
- fishing
- taming
- herbalism
- mining
- repair
- excavation
- woodcutting
drisgannpcs: 
- 138
- 140
- 141
- 144
- 145
- 146
- 147
- 148
- 150
- 167
- 168
helmets:
- leather_helmet
- chainmail_helmet
- iron_helmet
- golden_helmet
- diamond_helmet
chestplates:
- leather_chestplate
- chainmail_chestplate
- iron_chestplate
- golden_chestplate
- diamond_chestplate
leggings:
- leather_leggings
- chainmail_leggings
- iron_leggings
- golden_leggings
- diamond_leggings
boots:
- leather_boots
- chainmail_boots
- iron_boots
- golden_boots
- diamond_boots
swords:
- wooden_sword
- stone_sword
- iron_sword
- golden_sword
- diamond_sword
axes:
- wooden_axe
- stone_axe
- iron_axe
- golden_axe
- diamond_axe
attributes_armor:
- maxHealth
- knockbackResistance
- movementSpeed
- armor
attributes_weapons:
- maxHealth
- knockbackResistance
- movementSpeed
- attackDamage
- attackSpeed
items_lore2:
- peut
- peut peut-être
- peut sûrement
- pourrait
- pourrait peut-être
- pourrait sûrement
- devrait
- devrait sûrement
- doit sûrement
- semble
- semblerait
- saura sûrement
- saura peut être
items_lore3:
- aider.
- m'aider.
- venir en aide.
- être utile
- m'être utile.
- être pratique.
- servir à quelque chose.
- faire ses preuves.
enchantments:
- AbraKadaBra !
- Alakazam !
- Rhaich !
- Edro gûr lín.
- Belain na le !
- Calo anor na ven !
- Garo arad vaer !
- Nai haryuvalyë melwa rë.
- Noro go hûl, bado go Gaïa.
- I Anor hílol.
- Ná Gaïa veria le, ná elenath dín síla erin rád o chuil lín.
- I Melain berio le !
- No galu govad gen !
- No in elenath hîlar nan hâd gîn !