# -----------------------------------------------------------------------
#         Welcome to the main configuration of ChatControl
# -----------------------------------------------------------------------
# [General support and updates]
# http://www.spigotmc.org/resources/chatcontrol.271
# 
# [Default configuration with comments]
# https://github.com/kangarko/ChatControl/blob/master/config.yml
#
# [Tips]
# - Color codes are supported with the '&' character, see
#   http://minecraftwiki.net/wiki/Formatting_codes for usage
#
# - To not display a message, set it to 'none'.
#
# - Unicode /special characters/ only work when files are saved in 
#   UTF-8 encoding. Tested on Notepad++, WordPad on Windows is broken.
#
# - Most of the messages (warnings, etc) are found in the localization. 
#   To customize it, make a new file in "localization/messages_LOCALE.yml" 
#   (Replace LOCALE with the actuall locale name, by default 'en'). It
#   will be filled with all default values and kept with sync on updates.
# -----------------------------------------------------------------------

Anti_Bot:
  # Delay between player logging in again in seconds.
  Rejoin_Delay_Seconds: 1
  
  # Set if the player has to move from their join location to do following.
  Block_Actions_Until_Moved:
    # To be able to chat (player will still be able to execute commands)
    Chat: false

Anti_Caps:
  Enabled: true
  Warn_Player: false
  
  # Ignore player names. Exclude them from caps percentage and caps in a row check.
  # Enabling is not recommended on a bigger servers (50+ slots) due to iterating over every player (laggy).
  Ignore_Usernames: false
  Min_Message_Length: 5
  Min_Caps_Percentage: 50
  Min_Caps_In_A_Row: 5
  Whitelist:
  - OMG
  - LOL
  - WTF
  - WOW
  - ROFL

Anti_Spam:
  Similarity_Check:
    Ignore_Special_Characters: true
    Ignore_Duplicate_Characters: false
    
    # If enabled, the first and second arguments in longer commands will be ignored.
    # This makes the check less annoying in messages like /tell <player> message
    # where it ignores /tell and <player> name.
    Ignore_First_Arguments_In_Commands: true

  Commands:
    # Delay in seconds. Set to 0 to disable.
    Delay_Between_Commands: 0
    
    # If a message is similar (in percents) to the previous one, block it.
    # Set to 0 or 100 to disable.
    # We keep in mind that commands like /tell includes always name, making the check less annonying.
    Similar_Percentage_Block: 0
 
    # Commands ignored from the delay check.
    Whitelist_Similarity:
    - tell
    - pm
    - t
    - w
    - r
 
    # Commands ignored from the similarity check.
    Whitelist_Delay:
    - spawn
    - home

  Chat:
    # Delay in seconds. Set to 0 to disable.
    Delay_Between_Messages: 1

    # If a command is similar (in percents) to the previous one, block it.
    # Set to 0 or 100 to disable.
    Similar_Percentage_Block: 0
    
    # Should regular expressions be supported in Whitelist_Similarity and Whitelist_Delay?
    # ! Can lead to unexpected behavior.
    Regex_In_Whitelist: false
    
    # Message that starts with following strings will be ignored from the delay check.
    Whitelist_Similarity:
    - hello
    - hey
    
    # Message that starts with following strings will be ignored from the similarity check.
    Whitelist_Delay:
    - yes

Chat:
  # You need Vault to enable the formatter.
  Formatter:
    Enabled: false

    # Default chat message format.
    # The prefix has to include the 'pl_' because without it the plugin's prefix name will be given instead.
    Message_Format: '%pl_prefix%player:%pl_suffix %message'

    # If Ranged_Mode is enabled, this format is used when a message is printed to the global chat by prefixing it with '!'
    # NB: Player must also have the 'chatcontrol.chat.global' permission to speak to the global chat.
    Global_Message_Format: '&8[GLOBAL]&f %pl_prefix%player:%pl_suffix %message'

    # If Ranged_Mode is enabled, this format is used when a player with 'chatcontrol.chat.spy' permission receives ranged message
    # that he normally should't see.
    # To spy on private messages (e.g. /tell or /mail), use Essentials /socialspy feature.
    Spy_Message_Format: '&8SPY: [%world&8]&f %pl_prefix%player:%pl_suffix %message'

    # If enabled and a players write a message, it will only be sent to players
    # within distance of the player specified in Range
    Ranged_Mode: false
    
    # If you want the range for entire world, give everyone chatcontrol.chat.overrideranged permission.
    Range: 100.0

  Grammar:
    # Punctualize every sentence. Ignores URLs.
    Insert_Dot:
      Enabled: true
      Min_Message_Length: 10

    # Make the first letter of a sentence big. Ignores URLs.
    Capitalize:
      Enabled: true
      Min_Message_Length: 10

Clear:
  # Broadcast that the chat was wiped?
  Broadcast: false

  # Send only one message to staff instead of a bunch of blank lines.
  Do_Not_Clear_For_Staff: true

  # Amount of blank lines that will be printed in the console when it is cleared.
  Console_Lines_To_Clear: 300

Messages:
  # Use 'default' to not modify, 'hide' to not display or write a custom message
  # Variables: %player %pl_suffix %pl_prefix (when Vault is installed)
  # %countrycode and %countryname when AuthMe is installed
  Join: '&2%player &d&oest arrivé sur Gaïa.'
  Quit: '&2%player &d&oest parti de Gaïa.'
  Kick: default
  
  # Needs AuthMe-Reloaded. Only display quit message when the player has logged.
  # You can disable displaying join message in AuthMe itself by enabling 'delayJoinMessage' in its config
  Show_Quit_Only_When_Logged: true

  # Automatic message broadcaster.
  Timed:
    Enabled: false
    Random_Order: true
    
    # If random order is enabled, the messages will be put in a cache and not repeat until the cache is empty,
    # then it will be filled again and so on.
    Random_No_Repeat: true
    
    # Prefix and suffix supports variables %player (player name) and %world (world name)
    Prefix: ''
    Suffix: ''
    Delay_Seconds: 600

    # Timed messages per worlds.
    # By default every world includes global messages.
    Message_List:
      
      # Messages displayed in all worlds.
      global:
      #- '&f[&dAstuce&f] &dPour vous repérer, utilisez la Carte Interactive sur &awww.gaia-minecraft.enjin.com/gallery'
Mute:
  # Broadcast that the chat was mute?
  Broadcast: true

  # Hide the following messages when the chat is muted
  Silence:
    Join_Messages: true
    Quit_Messages: true
    Kick_Messages: true
    Death_Messages: true

  Disabled_Commands_During_Mute:
  - me
  - tell
  - msg
  - r
  - w

# Needs ProtocolLib
Packets:
  # Enables all features that requires ProtocolLib
  # e.g. packet rules, tab complete
  Enabled: true

  # Prevent tab complete in certain cases where it can reveal server info.
  # For more advanced configuration use Spigot and configure the function in spigot.yml
  Tab_Complete:
    Disable: true
    Disable_Only_In_Commands: true
    
    # If the written message/command contains space ' ', allow it.
    Allow_When_Message_Has_Space: true
    
    # Allow when the message length is above specific number. 
    # Not recommended as it might still reveal your server setup.
    Allow_When_Length_Above: 0

# Custom rules are found in rules/ folder inside your plugins folder.
Rules:
  # Enabled in chat?
  Check_Chat: true
  
  # Enabled in commands?
  Check_Commands: true

  # Enabled on signs?
  Check_Signs: true
  
  # Needs ProtocolLib. If enabled, messages will be checked against rules/packets.txt
  # which supports replacing even bukkit / plugin messages.
  Check_Packets: true
  
  Packets:
  
    # Since Minecraft 1.7x, every message is a chat component. Unpacking it will bring better/more expected results.
    # Disable if experiencing issues with chat formatting plugins. Messages with hover/click effects won't be checked.
    Deserialize_Json: true

Console:
  Filter:
    # Filter console messages specified below?
    Enabled: true
    
    # Remove certain messages from the server console.
    # Does not need to be whole message, just a part of the message you want to block.
    Filter_Console_Messages:
    - enregistrer
    - modifiermdp
    - ajoutermail
    - modifiermail
    - envoyermdp
    - thisisthepasswordaddercommand
    - thisisthepasswordchangercommand
    - thisistheemailaddercommand
    - thisisthechangerecoverycommand
    #- Reached end of stream for
    #- Connection reset
    #- lost connection
    #- Constructing new userfile from base player
    #- checking if
    #- ClosedChannelException
    #- Set mob damage to
    #- SET DATA
    #- died
    #- at io.
    #- at net.
    #- at java.
    #- at sun.
    #- at com.
    #- io.netty
    #- Caused by
    #- ...
    #- That player cannot be found
    #- Indiquez le surnom du joueur.
    #- java.lang.NoSuchFieldException
    #- java.lang.NullPointerException
    #- at me.jaime29010
    #- at org.bukkit.craftbukkit.v1_9_R2.scheduler
    #- at org.bukkit.inventory.ItemStack.<init>(ItemStack.java
    #- '[MythicMobs] == Error occured during parsing of following drop table string'
    #- An error occured while parsing a drop table.
    #- Title command successfully executed
    #- moved too quickly!
    #- #!#!

Signs:
  Duplication:
    # Player will be unable to place two signs with the same text.
    Deny_Signs_With_Same_Text: false
    Alert_Staff: true

    # Block the sign (cancel event) when a custom rule matches the text on it.
    # NOT related to duplication check but to the custom rules.
    Block_When_Violates_A_Rule: true

    # Drop sign as an item?
    Drop_Sign: true

# Plays a sound to a player that is mentioned.
Sound_Notify:
  Enabled: true
  
  # Play a sound to player only when their are afk? Checked from Essentials plugin.
  Notify_Only_When_Afk: false

  # Play a sound to player only when someone writes following characters before
  # their name: Set to none to play a sound when the players name is mentioned in the chat.
  Notify_Only_If_Prefixed_With: ''
  
  # Format: bukkit_sound_name, volume (float), pitch (float)
  # NB! In Minecraft 1.9, the sound names has changed! If you are using 1.8.x or older, the default sound name is 'CHICKEN_EGG_POP'
  # Sounds for 1.9+: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  # Sounds for <=1.8: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/Sound.java?until=be55b4f5b8274c1124fe957e6a3259789f6e9747 
  Sound: ENTITY_CHICKEN_EGG, 1F, 1.5F
  Enabled_In_Commands:
  - msg
  - tell
  - t
  - w
  - r

# Overrides some settings above.
# There are currently only two settings.
Groups:
  Enabled: false
  
  # If you add a player/group permission (e.g via PermissionsEx: /pex user <nick> add <perm>)
  # Then you will not need to reload ChatControl with /chc reload
  # Always checking has impact on performance and it is recommended to have it disabled.
  Always_Check_Updates: false
  
  Group_List:
   
    # Example usage. Give the player chatcontrol.group.trusted to make it working. 
    # As you can see, if you do not specify the value, the default will be used.
    trusted:
      Message_Delay: 0
    
    guest:
      Message_Delay: 4
      Command_Delay: 6
      
    vip:
      # Notice if you are an OP you need to negate those permissions
      # otherwise it will be applied on you, too!
      Join_Message: "&6[VIP] &e%player has joined the game"
      Leave_Message: "&6[VIP] &e%player has left the game"
      Kick_Message: none

Updater:
  Enabled: true
  Notify: false
  Download: false
  
  # Disable important announcements after the plugin has been loaded
  Check_Notes: true

Writer:
  # Save chat to file?
  Write_Chat_Communication: true
  Strip_Colors: true

  # Messages of following players will not get writed.
  Ignore_Players:
  - ignoredAdmin

  # Commands that will be saved along with chat messages.
  Write_Commands:
  - tell
  - message
  - whisper
  - w
  - r

Minimum_Players_To_Enable_Checks: 1
Op_Has_Permissions: true
Regex_Timeout_Milis: 250

# To customize a locale, make file in localization/messages_LOCALENAME.yml
# It will be filled with all the values.
# Current available locales: en (english), de (german), sk (slovak), cz (czech), fr (french) and es (spanish)
Locale: fr

# Time of some plugin's operations is measured.
# Print a message in the console if they take longer than specified millisecond time.
# Set to 0 to disable.
Log_Lag_Over_Milis: 250

# If a message was caught by a rule print info to the console.
# It is possible to hide individual packet rules from appearing
# with "dont verbose" operators. This currently works only on packet rules.
Verbose_Rules: true

# Removes certain messages from startup (reduces spam in the console)
# If you are having any issues, disable this and enable Verbose and Debug.
Silent_Startup: true

# Plugin saves some player data, such as their last message or command + date of writing them, for antispam to use.
# You can decide if these data should be reset when the player quits. Recommended in lobby (when on bungee), but not elsewhere.
Reset_Cache_On_Quit: false

# Set to true if the \n operator does not work for you.
# Before that, please ensure you've saved the file in an encoding that supports new line operator.
Enforce_New_Line: false

# Enable if you are having issues, will tell you detailed info in the console.
Debug: false

# Do not change this value, otherwise it will corrupt your plugin installation!
Version: 4