# TownyWands - Customizable modular GUI's | Written and maintained by FastFelix771, CEO of the UnityGaming Network. | https://www.unitygaming.de

# If you change the value below, it will reset your config. Don't do it.
configVersion: 1800

# Important Notes:
# If you dont know what 'metaID' means: its the last part of the full item id, for example: 17:3 , the metaID comes behind the ':', if the item you want to add has no metaID, set it to 0 (zero)
# Dont enter higher slot values than your inventory supports, so if your GUI has 18 slots, dont use values lower than 1 or higher than 18 or you will get bombed by a ton of errors :D
# If you want to add more languages, just add the fields: name_ , lore_ , commands_ , each followed by your wished langcode, for example: es_ES = Spanish | fr_FR = French
# You can find all supported languages and their langcodes on the GitHub page! :) -> https://github.com/FastFelix771/TownyWands/blob/master/README.md
# Should TownyWands send some anonymous data to mcstats.org? 

metrics: false
# If you wish to use auto-translating you only need to provide english text as base for all translations that are possible.
auto-translate: false

# If the english base-texts are missing, it will throw errors, but the default config contains english texts, so you should be able to use this feature without problems.
# The first translation will take some time, then it will save the translated data and re-use it on the next restart if the english entries hasn't changed.
cpu-threads: 4

# More threads will allow to parse more inventories at the same time.
# Should TownyWands check if theres a new version of the plugin? It will NOT download anything, it will just tell you if theres a newer version of the plugin!
checkForUpdates: false

# If you have a BungeeCord Proxy connected to this server, you can enable this feature to make /bungeetp working!
bungeecord: false

## HOW DOES THE COMMANDS WORK ##
# 
# /vsign {playername} t new {data}
#
# /vsign creates a virtual Sign where players can write something into.
# This allows TownyWands to handle user-input for its GUI's! 
#
# The parameter {data} will be replaced with the stuff the user typed on the virtual sign. (/vsign ONLY!)
#
# =========================
#
# /bungeetp {playername} myLobbyServer
#
# /bungeetp teleports the given player to another server inside your bungeecord network.
#
# The second parameter means the server the user should connect to, please type in the exact name from your bungeecord config to prevent errors!
#
# =========================
#
# Below is a full list of usable shortcuts, they work on both commands and console-commands in the configuration files.
#
#   {playername} = Player's name.
#	{uuid} = Player's UUID.
#	{world} = Name of the player's world.
#	{displayname} = Player's displayname.
#
################################